### ISSUE TITLE
Warn the user if there is a duplicated dom-module at compile time

### ISSUE THREAD

**Issue by samccone** [webpack-contrib/polymer-webpack-loader#25] opened 2017-07-15 02:18 UTC
This would be nice as compared to a runtime error :)

**Comment by ChadKillingsworth** [comment] 2017-07-15 02:40
Someone is thinking ahead ☺️

**Comment by ChadKillingsworth** [comment] 2017-07-15 14:42
I'm going to check in with some of the core webpack devs, but I suspect that this check will have to be a separate plugin. A loader typically only looks at a single file at a time and development standards warn about keeping state between them.

We're going to need a true webpack plugin or two. It's still a todo to figure out how to integrate the Polymer analyzer and linter. And I need Polymer-Rename for closure-compiler projects.

**Comment by web-padawan** [comment] 2017-07-18 16:46
The actual problem here is implementing bundling strategies, like `generateSharedDepsMergeStrategy` and maybe others from [polymer-bundler](https://github.com/Polymer/polymer-bundler/blob/master/src/bundle-manifest.ts#L233), isn't it?

**Comment by ChadKillingsworth** [comment] 2017-07-18 16:52
No the problem is `npm` doesn't create a flat dependency tree.

**Comment by ChadKillingsworth** [comment] 2017-08-14 17:16
@samccone I'm closing this as out of scope for a loader. It's still on my radar, but it would need to be a webpack plugin of some kind.

**Closed by ChadKillingsworth** 2017-08-14 17:16 UTC
