### ISSUE TITLE
Javascript variables from html imports are inaccessible after becoming module imports (polymer redux example)

### ISSUE THREAD

**Issue by zszafran** [webpack-contrib/polymer-webpack-loader#38] opened 2017-07-23 02:14 UTC
I'm trying to follow Rob's Redux Polycast while using this loader.

Maybe this is WAI but the javascript variables exposed from within html-imports are not accessible after they are made into module-imports.

This will fail with 'PolymerRedux' is undefined:
```html
<link rel="import" href="../bower_components/polymer-redux/polymer-redux.html">

<script type="text/javascript">
  const Redux = require('redux');

  const initial = {message: 'Hello, World!'};
  const reducer = state => state;
  const store = Redux.createStore(reducer, initial);

  const ReduxMixin = PolymerRedux(store);
</script>
```

And this would fail with 'ReduxMixin' is undefined:
```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="redux-store.html">

<dom-module id="app-main">
  <template>...</template>

  <script>
    class AppMain extends ReduxMixin(Polymer.Element) {

      static get is() { return 'app-main'; }

      static get properties() {
        return {};
      }
    }

    window.customElements.define(AppMain.is, AppMain);
  </script>
</dom-module>
```

My example project with a few quick attempts to make this work:
https://github.com/zszafran/polymer-redux-webpack/blob/master/src/redux-store.html

I was able to make part of this work by doing this:
```html
<link rel="import" href="../bower_components/polymer-redux/polymer-redux.html">

<script type="text/javascript">
  const Redux = require('redux');
  const initial = {message: 'Hello, World!'};
  const reducer = state => state;
  const store = Redux.createStore(reducer, initial);

  export const ReduxMixin = (Parent) => Parent;  // <--- added 'export'
</script>
```

```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="redux-store.html" imports="ReduxMixin">  <!-- added 'imports' attribute -->

<dom-module id="app-main">
  <template>...</template>

  <script>
    class AppMain extends ReduxMixin(Polymer.Element) {
      ...
    }

    window.customElements.define(AppMain.is, AppMain);
  </script>
</dom-module>
```

After I modified the loader:
```javascript
          if (ignoreLinks.indexOf(href) < 0 && ignoredFromPartial.length === 0) {
            var imports = (0, _dom.getAttribute)(linkNode, 'imports');
            var importStr = imports ? `{${imports}} from ` : '';
            source += `\nimport ${importStr}'${path.replace(/\\/g, '\\\\')}';\n`;
            lineCount += 2;
          }
```

But this hack only got me so far since I still need to modify polymer-redux to export the 'PolymerRedux' function. Maybe there is a FR in all this, but it seems like my best bet will be to load this all with ```<script>``` tags and somehow compile the polymer-redux source lib into it.

**Comment by ChadKillingsworth** [comment] 2017-07-23 10:55
This is expected behavior and by design. In WebPack everything is a module and variables declared at the root of a script are no longer global.

There are several two options to address this:

 1. Use the [WebPack shimming loaders and plugins](https://webpack.js.org/guides/shimming/). With shimming, WebPack will export specified symbols from a file and import others so they no longer have to be global.

 2. Change the web-component script tag to be `<script type="module">` and use the ES6 `import` and `export` statements to work with modules. This may not be the best option yet though since tooling in the Polymer project doesn't fully handle modules yet.

Feel free to post questions here regarding this, but I'm closing this as the behavior was expected.

**Closed by ChadKillingsworth** 2017-07-23 10:55 UTC

**Comment by cleaverpj** [comment] 2017-07-26 03:05
@ChadKillingsworth With regards to option 1, do you suggest using webpack.ProvidePlugin to make the redux mixin available globally, or using import and export loaders.

Should the redux mixin be changed from an HTML import to a JS file?

Would love to see a demo somewhere.

For option 2 which web-component script tag are you referring to?

**Comment by ChadKillingsworth** [comment] 2017-07-28 20:48
I have not forgotten about this. Just have to find time to put together an example.

**Comment by ChadKillingsworth** [comment] 2017-08-12 14:31
The actual easiest way to address this specific issue is to declare `ReduxMixin` as a property on the window object:

```html
<link rel="import" href="../bower_components/polymer-redux/polymer-redux.html">

<script type="text/javascript">
  const Redux = require('redux');

  const initial = {message: 'Hello, World!'};
  const reducer = state => state;
  const store = Redux.createStore(reducer, initial);

  window.ReduxMixin = PolymerRedux(store);
</script>
```

If you want to export it as a module, then make sure you add `type="module"` to the script tag.

```html
<link rel="import" href="../bower_components/polymer-redux/polymer-redux.html">

<script type="module">
  import Redux from 'redux';

  const initial = {message: 'Hello, World!'};
  const reducer = state => state;
  const store = Redux.createStore(reducer, initial);

  const ReduxMixin = PolymerRedux(store);
  export default ReduxMixin;
</script>
```

Then to use the import, you'd change your components:

```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<!-- <link rel="import" href="redux-store.html"> -->

<dom-module id="app-main">
  <template>...</template>

  <script type="module">
    import ReduxMixin from './redux-store.html';
    class AppMain extends ReduxMixin(Polymer.Element) {

      static get is() { return 'app-main'; }

      static get properties() {
        return {};
      }
    }

    window.customElements.define(AppMain.is, AppMain);
  </script>
</dom-module>
```

**Comment by NeilujD** [comment] 2018-03-19 16:41
@ChadKillingsworth I am not sure about the provided solution.
I think the issue is not about importing the `ReduxMixin` in the `app-main.html` element but importing the PolymerRedux mixin into the `redux-store.html` file. Am I right ?

**Comment by barnomics** [comment] 2018-06-15 21:19
I'm having the same issue, and yes, the issue is that `PolymerRedux` is not defined via `<link rel="import" href="../bower_components/polymer-redux/polymer-redux.html">`

**Comment by barnomics** [comment] 2018-06-15 22:05
woohoo I got this working!  Took quite a while but I'm able to apply the PolymerRedux mixin to components and dispatch events and what have you.  This would've been a lot easier if PolymerRedux was importable off the bat but here we are. 

If anyones interested let me know...

**Comment by thetrevlore** [comment] 2019-08-02 18:08
@barnomics I'm super interested! The OP's problem is my exact problem and @ChadKillingsworth's solution doesn't address it. How did you fix it?
