### ISSUE TITLE
BUG: embedded fonts in html component not working properly

### ISSUE THREAD

**Issue by constantijn** [webpack-contrib/polymer-webpack-loader#45] opened 2017-07-28 14:14 UTC
Hi,

When trying to use vaadin-grid component the icons in the header for sorting don't render properly when using polymer-webpack-loader they do work with the default polymer cli tools.

Steps to reproduce:

- Checkout webpack-polymer-loader
- cd demo
- update `webpack-polymer-loader` to 1.2.5 in package.json
- npm i && bower install
- bower install --save iron-ajax
- bower install --save vaadin-grid
- In demo/src/my-element.html add 
```
<link rel="import" href="../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid.html">
<link rel="import" href="../bower_components/vaadin-grid/vaadin-grid-sorter.html">
```
 at the top and 
``` 
<iron-ajax auto url="https://demo.vaadin.com/demo-data/1.0/people?count=10" handle-as="json" last-response="{{users}}"></iron-ajax>

<vaadin-grid items="[[users.result]]" style="width: 300px;">
  <vaadin-grid-column>
    <template class="header">
      <vaadin-grid-sorter path="firstName">First Name</vaadin-grid-sorter>
    </template>
    <template>[[item.firstName]]</template>
  </vaadin-grid-column>
  <vaadin-grid-column>
    <template class="header">
      <vaadin-grid-sorter path="lastName">Last Name</vaadin-grid-sorter>
    </template>
    <template>[[item.lastName]]</template>
  </vaadin-grid-column>
</vaadin-grid>
``` 
below the h1 in the template
- run `npm start`

Now the icons next to the first and lastname columns in the datagrid don't show up properly.

The font is embedded in the webcomponent here at line 29:
https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-sorter.html

For a working example click here and select the sorting and filtering demo:
https://vaadin.com/elements/-/element/vaadin-grid#demos

Anything i can do to get the font icons to show up properly? (Without locally hacking the vaadin-grid component)

**Comment by constantijn** [comment] 2017-07-28 14:17
**polymer-webpack-loader result **
![image](https://user-images.githubusercontent.com/926160/28721260-f7844c4e-73af-11e7-9316-a24fe17861f8.png)

**working example without polymer-webpack-loader **
![image](https://user-images.githubusercontent.com/926160/28721307-2278f936-73b0-11e7-8e1e-7431f81c2c20.png)

**Comment by bryandcoulter** [comment] 2017-07-28 15:09
@constantijn Thanks for filing the issue. Let me dig into this a bit and see what I can find.

**Comment by ChadKillingsworth** [comment] 2017-07-28 17:23
This is really a duplicate of #12. Closing in favor of that one, but thanks for the repo case!

**Closed by ChadKillingsworth** 2017-07-28 17:23 UTC
